default_chain: innuendo-3
chains:
  innuendo-3:
    key: default
    chain-id: innuendo-3
    rpc-addr: http://127.0.0.1:26658
    grpc-addr: http://127.0.0.1:9090
    account-prefix: quick
    keyring-backend: test
    gas-adjustment: 1.5
    gas-prices: 0.01uqck
    min-gas-amount: 0
    key-directory: /icq/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  elgafar-1:
    key: default
    chain-id: elgafar-1
    rpc-addr: http://127.0.0.1:26657
    grpc-addr: http://127.0.0.1:9090
    account-prefix: stars
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.00ustars
    min-gas-amount: 0
    key-directory: /icq/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct